package org.hmhb.url;

/**
 * Service to get the URL prefix for URLs generated by the server.
 */
public interface UrlService {

    /**
     * Returns the URL prefix for our server generated links.
     *
     * @return the URL prefix
     */
    String getUrlPrefix();

}
